name: api-tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    
jobs:
  api-tests:
    name: api-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black flake8 pytest-mypy
        pip install -r api/requirements.txt
    - name: Lint with black
      run: |
        black --check -l 120 .
    - name: Lint with flake8
      run: |
        flake8 --max-line-length 120
    - name: Test with pytest
      run: |
        pytest --mypy api/tests
